# Generated by Django 4.1.7 on 2023-02-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=20)),
                ('passward', models.CharField(max_length=20)),
            ],
        ),
    ]
