# Generated by Django 4.1.7 on 2023-02-26 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_branch_subjects_tests_questionbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='branch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.branch'),
        ),
    ]
