# Generated by Django 4.1.7 on 2023-02-27 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_professors_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisteredUser',
        ),
    ]
