# Generated by Django 4.1.7 on 2023-02-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_registereduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbank',
            name='subject',
        ),
        migrations.AddField(
            model_name='questionbank',
            name='subjectID',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
