# Generated by Django 4.1.7 on 2023-03-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_questionbank_subject_questionbank_subjectid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='numberOfQuestions',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='tests',
            name='testBufferTime',
            field=models.DurationField(default=None),
        ),
        migrations.AddField(
            model_name='tests',
            name='testDateTime',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='tests',
            name='testDuration',
            field=models.DurationField(default=None),
        ),
    ]
