# Generated by Django 4.1.7 on 2023-03-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_tests_numberofquestions_tests_testbuffertime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests',
            name='testDateTime',
        ),
        migrations.AddField(
            model_name='tests',
            name='testDate',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='tests',
            name='testTime',
            field=models.TimeField(default=None),
        ),
    ]
