# Generated by Django 4.1.7 on 2023-03-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_tests_testdatetime_tests_testdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tests',
            old_name='testTime',
            new_name='testEndTime',
        ),
        migrations.RemoveField(
            model_name='tests',
            name='testDuration',
        ),
        migrations.AddField(
            model_name='tests',
            name='testStartTime',
            field=models.TimeField(default=None),
        ),
    ]
