# Generated by Django 4.1.7 on 2023-03-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_testtime_tests_testendtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='testBufferTime',
            field=models.TimeField(default=None),
        ),
    ]
