# Generated by Django 4.1.7 on 2023-03-06 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='subject',
        ),
        migrations.AddField(
            model_name='questions',
            name='test',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.tests'),
        ),
    ]
