# Generated by Django 4.1.7 on 2023-03-06 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_questions_subject_questions_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='test',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tests'),
        ),
    ]
