# Generated by Django 4.1.7 on 2023-03-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_questions_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
