# Generated by Django 4.1.7 on 2023-03-06 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_questions_opt_1_alter_questions_opt_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testquestions',
            name='subject',
        ),
        migrations.AddField(
            model_name='testquestions',
            name='test',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.tests'),
        ),
    ]
