# Generated by Django 4.1.7 on 2023-03-06 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_testquestions_subject_testquestions_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
