# Generated by Django 4.1.7 on 2023-03-08 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_delete_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestions',
            name='subject',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.testsubject'),
        ),
        migrations.AlterField(
            model_name='testquestions',
            name='test',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tests'),
        ),
    ]
