# Generated by Django 4.1.7 on 2023-03-08 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_testquestions_subject_alter_testquestions_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestions',
            name='subject',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subjects'),
        ),
    ]
