# Generated by Django 4.1.7 on 2023-03-08 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_testquestions_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testquestions',
            name='test',
        ),
        migrations.DeleteModel(
            name='Tests',
        ),
    ]
