# Generated by Django 4.1.7 on 2023-03-08 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_testquestions_test_delete_tests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testName', models.CharField(max_length=20)),
                ('numberOfQuestions', models.IntegerField(default=None)),
                ('testDate', models.DateField(default=None)),
                ('testStartTime', models.TimeField(default=None)),
                ('testEndTime', models.TimeField(default=None)),
                ('testBufferTime', models.TimeField(default=None)),
                ('branch', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.branch')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subjects')),
            ],
        ),
    ]
