# Generated by Django 4.1.7 on 2023-03-08 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_testquestions_subject_questions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestQuestions',
        ),
        migrations.DeleteModel(
            name='TestSubject',
        ),
    ]
