# Generated by Django 4.1.7 on 2023-03-09 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_delete_testquestions_delete_testsubject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tests',
            new_name='TestDetails',
        ),
    ]
