# Generated by Django 4.1.7 on 2023-03-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_rename_tests_testdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testdetails',
            old_name='testDate',
            new_name='DateOfExam',
        ),
        migrations.RenameField(
            model_name='testdetails',
            old_name='testBufferTime',
            new_name='EndTime',
        ),
        migrations.RenameField(
            model_name='testdetails',
            old_name='testEndTime',
            new_name='StartTime',
        ),
        migrations.RemoveField(
            model_name='testdetails',
            name='testStartTime',
        ),
    ]
